SELECT ID, START_DATE, FINISH_DATE, DATEDIFF('MONTH', START_DATE, FINISH_DATE) AS DURATION_MONTHS
FROM project
GROUP BY ID, START_DATE, FINISH_DATE, DURATION_MONTHS
HAVING DURATION_MONTHS = (
    SELECT MAX(DATEDIFF('MONTH', START_DATE, FINISH_DATE))
    FROM project
)